apiVersion: v1
kind: Service
metadata:
  name: golang-service
  namespace: demo1
  labels:
    app: http-service
    version: v2
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: http-service
    version: v2
