apiVersion: v1
kind: Pod
metadata:
  name: err-probe-nginx
  namespace: demo1
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
      httpGet:
        path: /healthy
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /healthy
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3

