apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: demo1
  labels:
    app: http-service
    version: v3
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: http-service
    version: v3
